---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import variables
      include_vars: var-setup

    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{Cidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_hostnames: yes
        dns_support: yes
        tenancy: default
      register: vpc_out

    - name: create publlic subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1Cidr}}"
        map_public: yes
        state: "{{state}}"
        wait: yes
        tags:
          Name: pubsub1
      register: pubsub1_out



